from flask import Flask, request, make_response, jsonify, send_file, after_this_request
import pandas
import pdfkit
import htmlmin
import os
import datetime
app = Flask(__name__)
MYSTYLE = ""
PATH_TO_PDF = "/root/pdf_reports"
@app.route('/hello')
def hello():
    return 'Hello World'

@app.route("/api/csv_pdf", methods=["POST"])
def csv_pdf():
    if not request.files:
        return "{'message':'No files attached.'}", 400
    
    file = request.files["csv"]
    filename = file.filename.split(".")[0]
    if filename+'.pdf' in os.listdir('tmp'):
        return send_file(f"tmp/{filename}.pdf", download_name=f'{filename}.pdf')
    df = pandas.read_csv(file) 
    current_time = datetime.datetime.now()
    res = htmlmin.minify(f"<style>{MYSTYLE}</style><p>Report generated at : {current_time.strftime('%Y-%m-%d %H:%M')}</p>\
        {df.to_html(classes='mystyle')}<p>Report generated by Accops Reporting Server.</p>")
    pdfkit.from_string(res, f"{PATH_TO_PDF}/{filename}.pdf", options={"quiet": ""})
    return f"File saved as {PATH_TO_PDF}/{filename}.pdf", 200





if __name__ == "__main__":
    with open("mystyle.css", "r") as f:
        MYSTYLE = f.read()
    app.run(host='0.0.0.0', port=5000, debug=True)